name = "Musang"
license = "MIT"
licenselink = "https://github.com/fakhrullah/musang/blob/master/LICENSE.md"
description = "A simple theme based on Hyde theme with lot of customizable."
tags = ["blog", "simple"]
features = ["blog", "themes", "disqus"]
min_version = 0.14

[author]
  name = "fakhrullah"
  homepage = "https://fajarhac.com"
